% COMSOL Multiphysics Model M-file
% Generated by COMSOL 3.5a (COMSOL 3.5.0.608, $Date: 2009/05/11 07:38:49 $)

flclear fem

% COMSOL version
clear vrsn
vrsn.name = 'COMSOL 3.5';
vrsn.ext = 'a';
vrsn.major = 0;
vrsn.build = 608;
vrsn.rcs = '$Name: v35ap $';
vrsn.date = '$Date: 2009/05/11 07:38:49 $';
fem.version = vrsn;

% Geometry
g1=rect2(1,1,'base','corner','pos',[0,-0.8]);
g2=rect2('2.2','0.41','base','corner','pos',{'0','0'},'rot','0');
g3=ellip2(0.2,0.2,'base','center','pos',[-0.2,-0.2]);
g4=ellip2('0.05','0.05','base','center','pos',{'0.20','0.2'},'rot','0');
g5=geomcomp({g2,g4},'ns',{'R1','E1'},'sf','R1-E1','edge','none');

% Analyzed geometry
clear s
s.objs={g5};
s.name={'CO1'};
s.tags={'g5'};

fem.draw=struct('s',s);
fem.geom=geomcsg(fem);

% Constants
fem.const = {'Umax','0.3'};

% Constants
fem.const = {'Umax','0.3'};

% Constants
fem.const = {'Umax','0.3'};

% (Default values are not included)

% Application mode 1
clear appl
appl.mode.class = 'FlNavierStokes';
appl.gporder = {4,2};
appl.cporder = {2,1};
appl.sshape = 2;
appl.assignsuffix = '_ns';
clear prop
prop.analysis='static';
appl.prop = prop;
clear bnd
bnd.type = 'walltype';
bnd.ind = [1,1,1,1,1,1,1,1];
appl.bnd = bnd;
clear equ
equ.eta = 0.001;
equ.gporder = {{1;1;2}};
equ.cporder = {{1;1;2}};
equ.ind = [1];
appl.equ = equ;
fem.appl{1} = appl;
fem.frame = {'ref'};
fem.border = 1;
clear units;
units.basesystem = 'SI';
fem.units = units;

% ODE Settings
clear ode
clear units;
units.basesystem = 'SI';
ode.units = units;
fem.ode=ode;

% Multiphysics
fem=multiphysics(fem);

% COMSOL Multiphysics Model M-file
% Generated by COMSOL 3.5a (COMSOL 3.5.0.608, $Date: 2009/05/11 07:38:49 $)

% Initialize mesh
fem.mesh=meshinit(fem, ...
                  'hauto',5);

% (Default values are not included)

% Application mode 1
clear appl
appl.mode.class = 'FlNavierStokes';
appl.gporder = {4,2};
appl.cporder = {2,1};
appl.assignsuffix = '_ns';
clear prop
prop.analysis='static';
appl.prop = prop;
clear bnd
bnd.u0 = {0,'4*Umax*y*(0.41-y)/(0.41*0.41)',0};
bnd.type = {'walltype','inlet','outlet'};
bnd.velType = {'U0in','u0','U0in'};
bnd.outtype = {'p','p','ntotstress'};
bnd.ind = [2,1,1,3,1,1,1,1];
appl.bnd = bnd;
clear equ
equ.eta = 0.001;
equ.gporder = {{1;1;2}};
equ.cporder = {{1;1;2}};
equ.ind = [1];
appl.equ = equ;
fem.appl{1} = appl;
fem.frame = {'ref'};
fem.border = 1;
clear units;
units.basesystem = 'SI';
fem.units = units;

% ODE Settings
clear ode
clear units;
units.basesystem = 'SI';
ode.units = units;
fem.ode=ode;

% Multiphysics
fem=multiphysics(fem);

% Extend mesh
fem.xmesh=meshextend(fem);

% Solve problem
fem=adaption(fem, ...
             'symmetric','off', ...
             'solcomp',{'v','u','p'}, ...
             'outcomp',{'v','u','p'}, ...
             'blocksize','auto', ...
             'hnlin','on', ...
             'solver','stationary', ...
             'eigselect',1, ...
             'maxt',10000000, ...
             'ngen',3, ...
             'rmethod','longest', ...
             'resorder','auto', ...
             'eefun','l2', ...
             'l2scale',1, ...
             'l2staborder',2, ...
             'tppar',1.7, ...
             'linsolver','gmres', ...
             'maxlinit',100, ...
             'uscale','none', ...
             'geomnum',1);

% Save current fem structure for restart purposes
fem0=fem;

% Plot solution
postplot(fem, ...
         'tridata',{'U_ns','cont','internal','unit','m/s'}, ...
         'trimap','Rainbow', ...
         'title','Surface: Velocity field [m/s]', ...
         'axis',[-0.940318640854571,2.6703489007984254,-1.2642276422764234,1.1016260162601632]);

% Initialize mesh
fem.mesh=meshinit(fem, ...
                  'hauto',5);

% Initialize mesh
fem.mesh=meshinit(fem, ...
                  'hauto',5);

% (Default values are not included)

% Application mode 1
clear appl
appl.mode.class = 'FlNavierStokes';
appl.gporder = {4,2};
appl.cporder = {2,1};
appl.assignsuffix = '_ns';
clear prop
prop.analysis='static';
appl.prop = prop;
clear bnd
bnd.u0 = {0,'4*Umax*y*(0.41-y)/(0.41*0.41)',0};
bnd.type = {'walltype','inlet','outlet'};
bnd.velType = {'U0in','u0','U0in'};
bnd.outtype = {'p','p','ntotstress'};
bnd.ind = [2,1,1,3,1,1,1,1];
appl.bnd = bnd;
clear equ
equ.eta = 0.001;
equ.gporder = {{1;1;2}};
equ.cporder = {{1;1;2}};
equ.ind = [1];
appl.equ = equ;
fem.appl{1} = appl;
fem.frame = {'ref'};
fem.border = 1;
clear units;
units.basesystem = 'SI';
fem.units = units;

% ODE Settings
clear ode
clear units;
units.basesystem = 'SI';
ode.units = units;
fem.ode=ode;

% Multiphysics
fem=multiphysics(fem);

% Extend mesh
fem.xmesh=meshextend(fem);

% Solve problem
fem=adaption(fem, ...
             'symmetric','off', ...
             'solcomp',{'v','u','p'}, ...
             'outcomp',{'v','u','p'}, ...
             'blocksize','auto', ...
             'hnlin','on', ...
             'solver','stationary', ...
             'eigselect',1, ...
             'maxt',10000000, ...
             'ngen',3, ...
             'rmethod','longest', ...
             'resorder','auto', ...
             'eefun','l2', ...
             'l2scale',1, ...
             'l2staborder',2, ...
             'tppar',1.7, ...
             'uscale','none', ...
             'geomnum',1);

% Save current fem structure for restart purposes
fem0=fem;

% Plot solution
postplot(fem, ...
         'tridata',{'U_ns','cont','internal','unit','m/s'}, ...
         'trimap','Rainbow', ...
         'title','Surface: Velocity field [m/s]', ...
         'axis',[-0.940318640854571,2.6703489007984254,-1.2642276422764234,1.1016260162601632]);

% Integrate
I1=postint(fem,'p', ...
           'unit','Pa', ...
           'recover','off', ...
           'dl',1, ...
           'edim',0);

% Integrate
I2=postint(fem,'p', ...
           'unit','Pa', ...
           'recover','off', ...
           'dl',2, ...
           'edim',0);

% Integrate
I3=postint(fem,'p', ...
           'unit','Pa', ...
           'recover','off', ...
           'dl',3, ...
           'edim',0);

% Integrate
I4=postint(fem,'p', ...
           'unit','Pa', ...
           'recover','off', ...
           'dl',6, ...
           'edim',0);

% Integrate
I5=postint(fem,'T_x_ns', ...
           'unit','N/m', ...
           'recover','off', ...
           'dl',[5,6,7,8], ...
           'edim',1);

% Integrate
I6=postint(fem,'T_y_ns', ...
           'unit','N/m', ...
           'recover','off', ...
           'dl',[5,6,7,8], ...
           'edim',1);

return; %%%%%%%%%%% END OF HISTORY %%%%%%%%%%%%%%%%%%%%%%%
%                                                        %
% M-file below is used when resetting the model.         %
%                                                        %
%%%%%%%%%%%%%% START OF RESET HISTORY %%%%%%%%%%%%%%%%%%%%


% COMSOL Multiphysics Model M-file
% Generated by COMSOL 3.5a (COMSOL 3.5.0.608, $Date: 2009/05/11 07:38:49 $)

flclear fem

% COMSOL version
clear vrsn
vrsn.name = 'COMSOL 3.5';
vrsn.ext = 'a';
vrsn.major = 0;
vrsn.build = 608;
vrsn.rcs = '$Name: v35ap $';
vrsn.date = '$Date: 2009/05/11 07:38:49 $';
fem.version = vrsn;

% Geometry
g1=rect2(1,1,'base','corner','pos',[0,-0.8]);
g2=rect2('2.2','0.41','base','corner','pos',{'0','0'},'rot','0');
g3=ellip2(0.2,0.2,'base','center','pos',[-0.2,-0.2]);
g4=ellip2('0.05','0.05','base','center','pos',{'0.20','0.2'},'rot','0');
g5=geomcomp({g2,g4},'ns',{'R1','E1'},'sf','R1-E1','edge','none');

% Analyzed geometry
clear s
s.objs={g5};
s.name={'CO1'};
s.tags={'g5'};

fem.draw=struct('s',s);
fem.geom=geomcsg(fem);

% Constants
fem.const = {'Umax','0.3'};
