% COMSOL Multiphysics Model M-file
% Generated by COMSOL 3.5a (COMSOL 3.5.0.608, $Date: 2009/05/11 07:38:49 $)

flclear fem

% COMSOL version
clear vrsn
vrsn.name = 'COMSOL 3.5';
vrsn.ext = 'a';
vrsn.major = 0;
vrsn.build = 608;
vrsn.rcs = '$Name: v35ap $';
vrsn.date = '$Date: 2009/05/11 07:38:49 $';
fem.version = vrsn;

% Geometry
g1=rect2(1,1,'base','corner','pos',[0,-0.8]);
g2=rect2('2.2','0.41','base','corner','pos',{'0','0'},'rot','0');
g3=ellip2(0.2,0.2,'base','center','pos',[-0.2,-0.2]);
g4=ellip2('0.05','0.05','base','center','pos',{'0.20','0.2'},'rot','0');
g5=geomcomp({g2,g4},'ns',{'R1','E1'},'sf','R1-E1','edge','none');

% Analyzed geometry
clear s
s.objs={g5};
s.name={'CO1'};
s.tags={'g5'};

fem.draw=struct('s',s);
fem.geom=geomcsg(fem);

% Constants
fem.const = {'Umax','0.3'};

% Constants
fem.const = {'Umax','0.3'};

% Constants
fem.const = {'Umax','0.3'};

% (Default values are not included)

% Application mode 1
clear appl
appl.mode.class = 'FlNavierStokes';
appl.gporder = {4,2};
appl.cporder = {2,1};
appl.sshape = 2;
appl.assignsuffix = '_ns';
clear prop
prop.analysis='static';
appl.prop = prop;
clear bnd
bnd.type = 'walltype';
bnd.ind = [1,1,1,1,1,1,1,1];
appl.bnd = bnd;
clear equ
equ.eta = 0.001;
equ.gporder = {{1;1;2}};
equ.cporder = {{1;1;2}};
equ.ind = [1];
appl.equ = equ;
fem.appl{1} = appl;
fem.frame = {'ref'};
fem.border = 1;
clear units;
units.basesystem = 'SI';
fem.units = units;

% ODE Settings
clear ode
clear units;
units.basesystem = 'SI';
ode.units = units;
fem.ode=ode;

% Multiphysics
fem=multiphysics(fem);

return; %%%%%%%%%%% END OF HISTORY %%%%%%%%%%%%%%%%%%%%%%%
%                                                        %
% M-file below is used when resetting the model.         %
%                                                        %
%%%%%%%%%%%%%% START OF RESET HISTORY %%%%%%%%%%%%%%%%%%%%

% COMSOL Multiphysics Model M-file
% Generated by COMSOL 3.5a (COMSOL 3.5.0.608, $Date: 2009/05/11 07:38:49 $)

flclear fem

% COMSOL version
clear vrsn
vrsn.name = 'COMSOL 3.5';
vrsn.ext = 'a';
vrsn.major = 0;
vrsn.build = 608;
vrsn.rcs = '$Name: v35ap $';
vrsn.date = '$Date: 2009/05/11 07:38:49 $';
fem.version = vrsn;

% Geometry
g1=rect2(1,1,'base','corner','pos',[0,-0.8]);
g2=rect2('2.2','0.41','base','corner','pos',{'0','0'},'rot','0');
g3=ellip2(0.2,0.2,'base','center','pos',[-0.2,-0.2]);
g4=ellip2('0.05','0.05','base','center','pos',{'0.20','0.2'},'rot','0');
g5=geomcomp({g2,g4},'ns',{'R1','E1'},'sf','R1-E1','edge','none');

% Analyzed geometry
clear s
s.objs={g5};
s.name={'CO1'};
s.tags={'g5'};

fem.draw=struct('s',s);
fem.geom=geomcsg(fem);

% Constants
fem.const = {'Umax','0.3'};
