% COMSOL Multiphysics Model M-file
% Generated by COMSOL 3.5a (COMSOL 3.5.0.608, $Date: 2009/05/11 07:38:49 $)

flclear fem

% COMSOL version
clear vrsn
vrsn.name = 'COMSOL 3.5';
vrsn.ext = 'a';
vrsn.major = 0;
vrsn.build = 608;
vrsn.rcs = '$Name: v35ap $';
vrsn.date = '$Date: 2009/05/11 07:38:49 $';
fem.version = vrsn;

% Geometry
g1=rect2(1,1,'base','corner','pos',[0,-0.8]);
g2=rect2('2.2','0.41','base','corner','pos',{'0','0'},'rot','0');
g3=ellip2(0.2,0.2,'base','center','pos',[-0.2,-0.2]);
g4=ellip2('0.05','0.05','base','center','pos',{'0.20','0.2'},'rot','0');
g5=geomcomp({g2,g4},'ns',{'R1','E1'},'sf','R1-E1','edge','none');

% Analyzed geometry
clear s
s.objs={g5};
s.name={'CO1'};
s.tags={'g5'};

fem.draw=struct('s',s);
fem.geom=geomcsg(fem);

% Constants
fem.const = {'Umax','0.3'};

% Constants
fem.const = {'Umax','0.3'};

% Constants
fem.const = {'Umax','0.3'};

% (Default values are not included)

% Application mode 1
clear appl
appl.mode.class = 'FlNavierStokes';
appl.gporder = {4,2};
appl.cporder = {2,1};
appl.sshape = 2;
appl.assignsuffix = '_ns';
clear prop
prop.analysis='static';
appl.prop = prop;
clear bnd
bnd.type = 'walltype';
bnd.ind = [1,1,1,1,1,1,1,1];
appl.bnd = bnd;
clear equ
equ.eta = 0.001;
equ.gporder = {{1;1;2}};
equ.cporder = {{1;1;2}};
equ.ind = [1];
appl.equ = equ;
fem.appl{1} = appl;
fem.frame = {'ref'};
fem.border = 1;
clear units;
units.basesystem = 'SI';
fem.units = units;

% ODE Settings
clear ode
clear units;
units.basesystem = 'SI';
ode.units = units;
fem.ode=ode;

% Multiphysics
fem=multiphysics(fem);

% COMSOL Multiphysics Model M-file
% Generated by COMSOL 3.5a (COMSOL 3.5.0.608, $Date: 2009/05/11 07:38:49 $)

% Initialize mesh
fem.mesh=meshinit(fem, ...
                  'hauto',5);

% (Default values are not included)

% Application mode 1
clear appl
appl.mode.class = 'FlNavierStokes';
appl.gporder = {4,2};
appl.cporder = {2,1};
appl.assignsuffix = '_ns';
clear prop
prop.analysis='static';
appl.prop = prop;
clear bnd
bnd.u0 = {0,'4*Umax*y*(0.41-y)/(0.41*0.41)',0};
bnd.type = {'walltype','inlet','outlet'};
bnd.velType = {'U0in','u0','U0in'};
bnd.outtype = {'p','p','ntotstress'};
bnd.ind = [2,1,1,3,1,1,1,1];
appl.bnd = bnd;
clear equ
equ.eta = 0.001;
equ.gporder = {{1;1;2}};
equ.cporder = {{1;1;2}};
equ.ind = [1];
appl.equ = equ;
fem.appl{1} = appl;
fem.frame = {'ref'};
fem.border = 1;
clear units;
units.basesystem = 'SI';
fem.units = units;

% ODE Settings
clear ode
clear units;
units.basesystem = 'SI';
ode.units = units;
fem.ode=ode;

% Multiphysics
fem=multiphysics(fem);

% Extend mesh
fem.xmesh=meshextend(fem);

% Solve problem
fem=adaption(fem, ...
             'symmetric','off', ...
             'solcomp',{'v','u','p'}, ...
             'outcomp',{'v','u','p'}, ...
             'blocksize','auto', ...
             'hnlin','on', ...
             'solver','stationary', ...
             'eigselect',1, ...
             'maxt',10000000, ...
             'ngen',3, ...
             'rmethod','longest', ...
             'resorder','auto', ...
             'eefun','l2', ...
             'l2scale',1, ...
             'l2staborder',2, ...
             'tppar',1.7, ...
             'linsolver','gmres', ...
             'maxlinit',100, ...
             'uscale','none', ...
             'geomnum',1);

% Save current fem structure for restart purposes
fem0=fem;

% Plot solution
postplot(fem, ...
         'tridata',{'U_ns','cont','internal','unit','m/s'}, ...
         'trimap','Rainbow', ...
         'title','Surface: Velocity field [m/s]', ...
         'axis',[-0.940318640854571,2.6703489007984254,-1.2642276422764234,1.1016260162601632]);

% Initialize mesh
fem.mesh=meshinit(fem, ...
                  'hauto',5);

% Initialize mesh
fem.mesh=meshinit(fem, ...
                  'hauto',5);

% (Default values are not included)

% Application mode 1
clear appl
appl.mode.class = 'FlNavierStokes';
appl.gporder = {4,2};
appl.cporder = {2,1};
appl.assignsuffix = '_ns';
clear prop
prop.analysis='static';
appl.prop = prop;
clear bnd
bnd.u0 = {0,'4*Umax*y*(0.41-y)/(0.41*0.41)',0};
bnd.type = {'walltype','inlet','outlet'};
bnd.velType = {'U0in','u0','U0in'};
bnd.outtype = {'p','p','ntotstress'};
bnd.ind = [2,1,1,3,1,1,1,1];
appl.bnd = bnd;
clear equ
equ.eta = 0.001;
equ.gporder = {{1;1;2}};
equ.cporder = {{1;1;2}};
equ.ind = [1];
appl.equ = equ;
fem.appl{1} = appl;
fem.frame = {'ref'};
fem.border = 1;
clear units;
units.basesystem = 'SI';
fem.units = units;

% ODE Settings
clear ode
clear units;
units.basesystem = 'SI';
ode.units = units;
fem.ode=ode;

% Multiphysics
fem=multiphysics(fem);

% Extend mesh
fem.xmesh=meshextend(fem);

% Solve problem
fem=adaption(fem, ...
             'symmetric','off', ...
             'solcomp',{'v','u','p'}, ...
             'outcomp',{'v','u','p'}, ...
             'blocksize','auto', ...
             'hnlin','on', ...
             'solver','stationary', ...
             'eigselect',1, ...
             'maxt',10000000, ...
             'ngen',3, ...
             'rmethod','longest', ...
             'resorder','auto', ...
             'eefun','l2', ...
             'l2scale',1, ...
             'l2staborder',2, ...
             'tppar',1.7, ...
             'uscale','none', ...
             'geomnum',1);

% Save current fem structure for restart purposes
fem0=fem;

% Plot solution
postplot(fem, ...
         'tridata',{'U_ns','cont','internal','unit','m/s'}, ...
         'trimap','Rainbow', ...
         'title','Surface: Velocity field [m/s]', ...
         'axis',[-0.940318640854571,2.6703489007984254,-1.2642276422764234,1.1016260162601632]);

% Integrate
I1=postint(fem,'p', ...
           'unit','Pa', ...
           'recover','off', ...
           'dl',1, ...
           'edim',0);

% Integrate
I2=postint(fem,'p', ...
           'unit','Pa', ...
           'recover','off', ...
           'dl',2, ...
           'edim',0);

% Integrate
I3=postint(fem,'p', ...
           'unit','Pa', ...
           'recover','off', ...
           'dl',3, ...
           'edim',0);

% Integrate
I4=postint(fem,'p', ...
           'unit','Pa', ...
           'recover','off', ...
           'dl',6, ...
           'edim',0);

% Integrate
I5=postint(fem,'T_x_ns', ...
           'unit','N/m', ...
           'recover','off', ...
           'dl',[5,6,7,8], ...
           'edim',1);

% Integrate
I6=postint(fem,'T_y_ns', ...
           'unit','N/m', ...
           'recover','off', ...
           'dl',[5,6,7,8], ...
           'edim',1);


% COMSOL Multiphysics Model M-file
% Generated by COMSOL 3.5a (COMSOL 3.5.0.608, $Date: 2009/05/11 07:38:49 $)

% Constants
fem.const = {'Umax','3.0'};

% Constants
fem.const = {'Umax','3.0'};

% (Default values are not included)

% Application mode 1
clear appl
appl.mode.class = 'FlNavierStokes';
appl.gporder = {4,2};
appl.cporder = {2,1};
appl.assignsuffix = '_ns';
clear prop
prop.analysis='static';
appl.prop = prop;
clear bnd
bnd.u0 = {'4*Umax*y*(0.41-y)/(0.41*0.41)',0,0};
bnd.type = {'inlet','walltype','outlet'};
bnd.velType = {'u0','U0in','U0in'};
bnd.outtype = {'p','p','ntotstress'};
bnd.ind = [1,2,2,3,2,2,2,2];
appl.bnd = bnd;
clear equ
equ.eta = 0.001;
equ.gporder = {{1;1;2}};
equ.cporder = {{1;1;2}};
equ.ind = [1];
appl.equ = equ;
fem.appl{1} = appl;
fem.frame = {'ref'};
fem.border = 1;
clear units;
units.basesystem = 'SI';
fem.units = units;

% ODE Settings
clear ode
clear units;
units.basesystem = 'SI';
ode.units = units;
fem.ode=ode;

% Multiphysics
fem=multiphysics(fem);

% Extend mesh
fem.xmesh=meshextend(fem);

% Solve problem
fem=adaption(fem, ...
             'symmetric','off', ...
             'solcomp',{'v','u','p'}, ...
             'outcomp',{'v','u','p'}, ...
             'blocksize','auto', ...
             'hnlin','on', ...
             'solver','stationary', ...
             'eigselect',1, ...
             'maxt',10000000, ...
             'ngen',3, ...
             'rmethod','longest', ...
             'resorder','auto', ...
             'eefun','l2', ...
             'l2scale',1, ...
             'l2staborder',2, ...
             'tppar',1.7, ...
             'uscale','none', ...
             'geomnum',1);

% Save current fem structure for restart purposes
fem0=fem;

% Plot solution
postplot(fem, ...
         'tridata',{'U_ns','cont','internal','unit','m/s'}, ...
         'trimap','Rainbow', ...
         'title','Surface: Velocity field [m/s]', ...
         'axis',[-0.9789059275592596,2.7089361875031144,-1.2642276422764234,1.1016260162601632]);

% Plot solution
postplot(fem, ...
         'tridata',{'U_ns','cont','internal','unit','m/s'}, ...
         'triedgestyle','interp', ...
         'trifacestyle','none', ...
         'trimap','Rainbow', ...
         'title','Surface: Velocity field [m/s]', ...
         'axis',[-0.022254452491842096,2.035210154132386,-0.5263565307182281,0.9103591594084983]);

% Plot solution
postplot(fem, ...
         'tridata',{'U_ns','cont','internal','unit','m/s'}, ...
         'triedgestyle','interp', ...
         'trifacestyle','none', ...
         'trimap','Rainbow', ...
         'title','Surface: Velocity field [m/s]', ...
         'axis',[-0.022254452491842096,2.035210154132386,-0.5263565307182281,0.9103591594084983]);

% (Default values are not included)

% Application mode 1
clear appl
appl.mode.class = 'FlNavierStokes';
appl.gporder = {4,2};
appl.cporder = {2,1};
appl.assignsuffix = '_ns';
clear bnd
bnd.u0 = {'4*Umax*y*(0.41-y)/(0.41*0.41)',0,0};
bnd.type = {'inlet','walltype','outlet'};
bnd.velType = {'u0','U0in','U0in'};
bnd.outtype = {'p','p','ntotstress'};
bnd.ind = [1,2,2,3,2,2,2,2];
appl.bnd = bnd;
clear equ
equ.eta = 0.001;
equ.gporder = {{1;1;2}};
equ.cporder = {{1;1;2}};
equ.ind = [1];
appl.equ = equ;
fem.appl{1} = appl;
fem.frame = {'ref'};
fem.border = 1;
clear units;
units.basesystem = 'SI';
fem.units = units;

% ODE Settings
clear ode
clear units;
units.basesystem = 'SI';
ode.units = units;
fem.ode=ode;

% Multiphysics
fem=multiphysics(fem);

% COMSOL Multiphysics Model M-file
% Generated by COMSOL 3.5a (COMSOL 3.5.0.608, $Date: 2009/05/11 07:38:49 $)

% Initialize mesh
fem.mesh=meshinit(fem, ...
                  'hauto',5);

% (Default values are not included)

% Application mode 1
clear appl
appl.mode.class = 'FlNavierStokes';
appl.gporder = {4,2};
appl.cporder = {2,1};
appl.sshape = 2;
appl.assignsuffix = '_ns';
clear bnd
bnd.u0 = {'4*Umax*y*(0.41-y)/(0.41*0.41)',0,0};
bnd.type = {'inlet','walltype','outlet'};
bnd.velType = {'u0','U0in','U0in'};
bnd.outtype = {'p','p','ntotstress'};
bnd.ind = [1,2,2,3,2,2,2,2];
appl.bnd = bnd;
clear equ
equ.eta = 0.001;
equ.gporder = {{1;1;2}};
equ.cporder = {{1;1;2}};
equ.cdon = 0;
equ.sdon = 0;
equ.ind = [1];
appl.equ = equ;
fem.appl{1} = appl;
fem.frame = {'ref'};
fem.border = 1;
clear units;
units.basesystem = 'SI';
fem.units = units;

% ODE Settings
clear ode
clear units;
units.basesystem = 'SI';
ode.units = units;
fem.ode=ode;

% Multiphysics
fem=multiphysics(fem);

% Extend mesh
fem.xmesh=meshextend(fem);

% Solve problem
fem=adaption(fem, ...
             'symmetric','off', ...
             'solcomp',{'v','u','p'}, ...
             'outcomp',{'v','u','p'}, ...
             'blocksize','auto', ...
             'hnlin','on', ...
             'solver','stationary', ...
             'eigselect',1, ...
             'maxt',10000000, ...
             'ngen',3, ...
             'rmethod','longest', ...
             'resorder','auto', ...
             'eefun','l2', ...
             'l2scale',1, ...
             'l2staborder',2, ...
             'tppar',1.7, ...
             'uscale','none', ...
             'geomnum',1);

% Save current fem structure for restart purposes
fem0=fem;

% Plot solution
postplot(fem, ...
         'tridata',{'U_ns','cont','internal','unit','m/s'}, ...
         'triedgestyle','interp', ...
         'trifacestyle','none', ...
         'trimap','Rainbow', ...
         'title','Surface: Velocity field [m/s]', ...
         'axis',[-0.0898500412719461,2.1028057429124902,-0.5263565307182281,0.9103591594084983]);

% Initialize mesh
fem.mesh=meshinit(fem, ...
                  'hauto',5);

% (Default values are not included)

% Application mode 1
clear appl
appl.mode.class = 'FlNavierStokes';
appl.gporder = {4,2};
appl.cporder = {2,1};
appl.sshape = 2;
appl.assignsuffix = '_ns';
clear prop
prop.analysis='static';
appl.prop = prop;
clear bnd
bnd.u0 = {'4*Umax*y*(0.41-y)/(0.41*0.41)',0,0};
bnd.type = {'inlet','walltype','outlet'};
bnd.velType = {'u0','U0in','U0in'};
bnd.outtype = {'p','p','ntotstress'};
bnd.ind = [1,2,2,3,2,2,2,2];
appl.bnd = bnd;
clear equ
equ.eta = 0.001;
equ.gporder = {{1;1;2}};
equ.cporder = {{1;1;2}};
equ.cdon = 0;
equ.sdon = 0;
equ.ind = [1];
appl.equ = equ;
fem.appl{1} = appl;
fem.frame = {'ref'};
fem.border = 1;
clear units;
units.basesystem = 'SI';
fem.units = units;

% ODE Settings
clear ode
clear units;
units.basesystem = 'SI';
ode.units = units;
fem.ode=ode;

% Multiphysics
fem=multiphysics(fem);

% Extend mesh
fem.xmesh=meshextend(fem);

% Solve problem
fem=adaption(fem, ...
             'symmetric','off', ...
             'solcomp',{'v','u','p'}, ...
             'outcomp',{'v','u','p'}, ...
             'blocksize','auto', ...
             'hnlin','on', ...
             'solver','stationary', ...
             'eigselect',1, ...
             'maxt',10000000, ...
             'ngen',3, ...
             'rmethod','longest', ...
             'resorder','auto', ...
             'eefun','l2', ...
             'l2scale',1, ...
             'l2staborder',2, ...
             'tppar',1.7, ...
             'uscale','none', ...
             'geomnum',1);

% Save current fem structure for restart purposes
fem0=fem;

% Plot solution
postplot(fem, ...
         'tridata',{'U_ns','cont','internal','unit','m/s'}, ...
         'triedgestyle','interp', ...
         'trifacestyle','none', ...
         'trimap','Rainbow', ...
         'title','Surface: Velocity field [m/s]', ...
         'axis',[-0.1100000023841858,2.3100000500679014,-0.5878403715679857,0.997840367991707]);

% Initialize mesh
fem.mesh=meshinit(fem, ...
                  'hauto',5);

% (Default values are not included)

% Application mode 1
clear appl
appl.mode.class = 'FlNavierStokes';
appl.gporder = {4,2};
appl.cporder = {2,1};
appl.sshape = 2;
appl.assignsuffix = '_ns';
clear bnd
bnd.u0 = {'4*Umax*y*(0.41-y)/(0.41*0.41)',0,0};
bnd.type = {'inlet','walltype','outlet'};
bnd.velType = {'u0','U0in','U0in'};
bnd.outtype = {'p','p','ntotstress'};
bnd.ind = [1,2,2,3,2,2,2,2];
appl.bnd = bnd;
clear equ
equ.eta = 0.001;
equ.gporder = {{1;1;2}};
equ.cporder = {{1;1;2}};
equ.cdon = 0;
equ.sdon = 0;
equ.ind = [1];
appl.equ = equ;
fem.appl{1} = appl;
fem.frame = {'ref'};
fem.border = 1;
clear units;
units.basesystem = 'SI';
fem.units = units;

% ODE Settings
clear ode
clear units;
units.basesystem = 'SI';
ode.units = units;
fem.ode=ode;

% Multiphysics
fem=multiphysics(fem);

% Extend mesh
fem.xmesh=meshextend(fem);

% Solve problem
fem.sol=femtime(fem, ...
                'symmetric','off', ...
                'solcomp',{'v','u','p'}, ...
                'outcomp',{'v','u','p'}, ...
                'blocksize','auto', ...
                'odesolver','genalpha', ...
                'tlist',[colon(0,0.025,3.5)], ...
                'estrat',1, ...
                'tout','tlist', ...
                'tsteps','manual', ...
                'rhoinf',0.5, ...
                'timestep','5*dt_cfl_g1_ns', ...
                'nlsolver','manual', ...
                'ntolfact',1, ...
                'maxiter',5, ...
                'dtech','const', ...
                'damp',1.0, ...
                'jtech','once', ...
                'uscale','none');

% Save current fem structure for restart purposes
fem0=fem;

% Plot solution
postplot(fem, ...
         'tridata',{'U_ns','cont','internal','unit','m/s'}, ...
         'triedgestyle','interp', ...
         'trifacestyle','none', ...
         'trimap','Rainbow', ...
         'solnum','end', ...
         'title','Time=3.5    Surface: Velocity field [m/s]', ...
         'axis',[-0.1100000023841858,2.3100000500679014,-0.5878403715679857,0.997840367991707]);

% Initialize mesh
fem.mesh=meshinit(fem, ...
                  'hauto',5);

% Refine mesh
fem.mesh=meshrefine(fem, ...
                    'mcase',0, ...
                    'rmethod','regular');

% (Default values are not included)

% Application mode 1
clear appl
appl.mode.class = 'FlNavierStokes';
appl.gporder = {4,2};
appl.cporder = {2,1};
appl.sshape = 2;
appl.assignsuffix = '_ns';
clear bnd
bnd.u0 = {'4*Umax*y*(0.41-y)/(0.41*0.41)',0,0};
bnd.type = {'inlet','walltype','outlet'};
bnd.velType = {'u0','U0in','U0in'};
bnd.outtype = {'p','p','ntotstress'};
bnd.ind = [1,2,2,3,2,2,2,2];
appl.bnd = bnd;
clear equ
equ.eta = 0.001;
equ.gporder = {{1;1;2}};
equ.cporder = {{1;1;2}};
equ.cdon = 0;
equ.sdon = 0;
equ.ind = [1];
appl.equ = equ;
fem.appl{1} = appl;
fem.frame = {'ref'};
fem.border = 1;
clear units;
units.basesystem = 'SI';
fem.units = units;

% ODE Settings
clear ode
clear units;
units.basesystem = 'SI';
ode.units = units;
fem.ode=ode;

% Multiphysics
fem=multiphysics(fem);

% Extend mesh
fem.xmesh=meshextend(fem);

% Solve problem
fem.sol=femtime(fem, ...
                'symmetric','off', ...
                'solcomp',{'v','u','p'}, ...
                'outcomp',{'v','u','p'}, ...
                'blocksize','auto', ...
                'odesolver','genalpha', ...
                'tlist',[colon(0,0.025,3.5)], ...
                'estrat',1, ...
                'tout','tlist', ...
                'tsteps','manual', ...
                'rhoinf',0.5, ...
                'timestep','5*dt_cfl_g1_ns', ...
                'nlsolver','manual', ...
                'ntolfact',1, ...
                'maxiter',5, ...
                'dtech','const', ...
                'damp',1.0, ...
                'jtech','once', ...
                'uscale','none');

% Save current fem structure for restart purposes
fem0=fem;

% Plot solution
postplot(fem, ...
         'tridata',{'U_ns','cont','internal','unit','m/s'}, ...
         'triedgestyle','interp', ...
         'trifacestyle','none', ...
         'trimap','Rainbow', ...
         'solnum','end', ...
         'title','Time=3.5    Surface: Velocity field [m/s]', ...
         'axis',[-0.1100000023841858,2.3100000500679014,-0.5878403715679857,0.997840367991707]);

% COMSOL Multiphysics Model M-file
% Generated by COMSOL 3.5a (COMSOL 3.5.0.608, $Date: 2009/05/11 07:38:49 $)

% Plot solution
postplot(fem, ...
         'tridata',{'U_ns','cont','internal','unit','m/s'}, ...
         'trimap','Rainbow', ...
         'solnum','end', ...
         'title','Time=3.5    Surface: Velocity field [m/s]', ...
         'axis',[-0.1100000023841858,7.4872617759739555,-3.741552654564525,1.767053821799516]);

% Plot solution
postplot(fem, ...
         'tridata',{'U_ns','cont','internal','unit','m/s'}, ...
         'trimap','Rainbow', ...
         'solnum','end', ...
         'title','Time=3.5    Surface: Velocity field [m/s]', ...
         'axis',[-0.1100000023841858,7.4872617759739555,-3.741552654564525,1.767053821799516]);

% (Default values are not included)

% Application mode 1
clear appl
appl.mode.class = 'FlNavierStokes';
appl.gporder = {4,2};
appl.cporder = {2,1};
appl.assignsuffix = '_ns';
clear bnd
bnd.u0 = {'4*Umax*y*(0.41-y)/(0.41*0.41)',0,0};
bnd.type = {'inlet','walltype','outlet'};
bnd.velType = {'u0','U0in','U0in'};
bnd.outtype = {'p','p','ntotstress'};
bnd.ind = [1,2,2,3,2,2,2,2];
appl.bnd = bnd;
clear equ
equ.eta = 0.001;
equ.gporder = {{1;1;2}};
equ.cporder = {{1;1;2}};
equ.cdon = 0;
equ.sdon = 0;
equ.ind = [1];
appl.equ = equ;
fem.appl{1} = appl;
fem.frame = {'ref'};
fem.border = 1;
clear units;
units.basesystem = 'SI';
fem.units = units;

% Coupling variable elements
clear elemcpl
% Integration coupling variables
clear elem
elem.elem = 'elcplscalar';
elem.g = {'1'};
src = cell(1,1);
clear bnd
bnd.expr = {{{},'T_y_ns'}};
bnd.ipoints = {{{},'4'}};
bnd.frame = {{{},'ref'}};
bnd.ind = {{'1','2','3','4'},{'5','6','7','8'}};
src{1} = {{},bnd,{}};
elem.src = src;
geomdim = cell(1,1);
geomdim{1} = {};
elem.geomdim = geomdim;
elem.var = {'tyns'};
elem.global = {'1'};
elemcpl{1} = elem;
fem.elemcpl = elemcpl;

% ODE Settings
clear ode
clear units;
units.basesystem = 'SI';
ode.units = units;
fem.ode=ode;

% Multiphysics
fem=multiphysics(fem);

% Extend mesh
fem.xmesh=meshextend(fem);

% Mapping current solution to extended mesh
init = asseminit(fem,'init',fem0.sol,'solnum',1:solsize(fem0.sol),'blocksize','auto');

% Update model
fem.sol = init;

% Save current fem structure for restart purposes
fem0=fem;

% Plot solution
postplot(fem, ...
         'tridata',{'U_ns','cont','internal','unit','m/s'}, ...
         'trimap','Rainbow', ...
         'solnum','end', ...
         'title','Time=3.5    Surface: Velocity field [m/s]', ...
         'axis',[-0.1100000023841858,2.3100000500679014,-0.6190746355968055,1.0290746320205268]);

% Initialize mesh
fem.mesh=meshinit(fem, ...
                  'hauto',5);

% Initialize mesh
fem.mesh=meshinit(fem, ...
                  'hauto',5);

% (Default values are not included)

% Application mode 1
clear appl
appl.mode.class = 'FlNavierStokes';
appl.gporder = {4,2};
appl.cporder = {2,1};
appl.assignsuffix = '_ns';
clear bnd
bnd.u0 = {'4*Umax*y*(0.41-y)/(0.41*0.41)',0,0};
bnd.type = {'inlet','walltype','outlet'};
bnd.velType = {'u0','U0in','U0in'};
bnd.outtype = {'p','p','ntotstress'};
bnd.ind = [1,2,2,3,2,2,2,2];
appl.bnd = bnd;
clear equ
equ.eta = 0.001;
equ.gporder = {{1;1;2}};
equ.cporder = {{1;1;2}};
equ.cdon = 0;
equ.sdon = 0;
equ.ind = [1];
appl.equ = equ;
fem.appl{1} = appl;
fem.frame = {'ref'};
fem.border = 1;
clear units;
units.basesystem = 'SI';
fem.units = units;

% Coupling variable elements
clear elemcpl
% Integration coupling variables
clear elem
elem.elem = 'elcplscalar';
elem.g = {'1'};
src = cell(1,1);
clear bnd
bnd.expr = {{{},'T_y_ns'}};
bnd.ipoints = {{{},'4'}};
bnd.frame = {{{},'ref'}};
bnd.ind = {{'1','2','3','4'},{'5','6','7','8'}};
src{1} = {{},bnd,{}};
elem.src = src;
geomdim = cell(1,1);
geomdim{1} = {};
elem.geomdim = geomdim;
elem.var = {'tyns'};
elem.global = {'1'};
elemcpl{1} = elem;
fem.elemcpl = elemcpl;

% ODE Settings
clear ode
clear units;
units.basesystem = 'SI';
ode.units = units;
fem.ode=ode;

% Multiphysics
fem=multiphysics(fem);

% Extend mesh
fem.xmesh=meshextend(fem);

% Solve problem
fem.sol=femtime(fem, ...
                'symmetric','off', ...
                'solcomp',{'v','u','p'}, ...
                'outcomp',{'v','u','p'}, ...
                'blocksize','auto', ...
                'odesolver','genalpha', ...
                'tlist',[colon(0,0.025,3.5)], ...
                'estrat',1, ...
                'tout','tlist', ...
                'tsteps','manual', ...
                'rhoinf',0.5, ...
                'timestep','5*dt_cfl_g1_ns', ...
                'nlsolver','manual', ...
                'ntolfact',1, ...
                'maxiter',5, ...
                'dtech','const', ...
                'damp',1.0, ...
                'jtech','once', ...
                'uscale','none');

% Save current fem structure for restart purposes
fem0=fem;

% Plot solution
postplot(fem, ...
         'tridata',{'U_ns','cont','internal','unit','m/s'}, ...
         'trimap','Rainbow', ...
         'solnum','end', ...
         'title','Time=3.5    Surface: Velocity field [m/s]', ...
         'axis',[-0.1100000023841858,2.3100000500679014,-0.6314667353533269,1.041466731777048]);

% Initialize mesh
fem.mesh=meshinit(fem, ...
                  'hauto',5);

% Refine mesh
fem.mesh=meshrefine(fem, ...
                    'mcase',0, ...
                    'rmethod','regular');

% (Default values are not included)

% Application mode 1
clear appl
appl.mode.class = 'FlNavierStokes';
appl.gporder = {4,2};
appl.cporder = {2,1};
appl.assignsuffix = '_ns';
clear bnd
bnd.u0 = {'4*Umax*y*(0.41-y)/(0.41*0.41)',0,0};
bnd.type = {'inlet','walltype','outlet'};
bnd.velType = {'u0','U0in','U0in'};
bnd.outtype = {'p','p','ntotstress'};
bnd.ind = [1,2,2,3,2,2,2,2];
appl.bnd = bnd;
clear equ
equ.eta = 0.001;
equ.gporder = {{1;1;2}};
equ.cporder = {{1;1;2}};
equ.cdon = 0;
equ.sdon = 0;
equ.ind = [1];
appl.equ = equ;
fem.appl{1} = appl;
fem.frame = {'ref'};
fem.border = 1;
clear units;
units.basesystem = 'SI';
fem.units = units;

% Coupling variable elements
clear elemcpl
% Integration coupling variables
clear elem
elem.elem = 'elcplscalar';
elem.g = {'1'};
src = cell(1,1);
clear bnd
bnd.expr = {{{},'T_y_ns'}};
bnd.ipoints = {{{},'4'}};
bnd.frame = {{{},'ref'}};
bnd.ind = {{'1','2','3','4'},{'5','6','7','8'}};
src{1} = {{},bnd,{}};
elem.src = src;
geomdim = cell(1,1);
geomdim{1} = {};
elem.geomdim = geomdim;
elem.var = {'tyns'};
elem.global = {'1'};
elemcpl{1} = elem;
fem.elemcpl = elemcpl;

% ODE Settings
clear ode
clear units;
units.basesystem = 'SI';
ode.units = units;
fem.ode=ode;

% Multiphysics
fem=multiphysics(fem);

% Extend mesh
fem.xmesh=meshextend(fem);

% Solve problem
fem.sol=femtime(fem, ...
                'symmetric','off', ...
                'solcomp',{'v','u','p'}, ...
                'outcomp',{'v','u','p'}, ...
                'blocksize','auto', ...
                'odesolver','genalpha', ...
                'tlist',[colon(0,0.025,3.5)], ...
                'estrat',1, ...
                'tout','tlist', ...
                'tsteps','manual', ...
                'rhoinf',0.5, ...
                'timestep','5*dt_cfl_g1_ns', ...
                'nlsolver','manual', ...
                'ntolfact',1, ...
                'maxiter',5, ...
                'dtech','const', ...
                'damp',1.0, ...
                'jtech','once', ...
                'uscale','none');

% Save current fem structure for restart purposes
fem0=fem;

% Plot solution
postplot(fem, ...
         'tridata',{'U_ns','cont','internal','unit','m/s'}, ...
         'trimap','Rainbow', ...
         'solnum','end', ...
         'title','Time=3.5    Surface: Velocity field [m/s]', ...
         'axis',[-0.1100000023841858,2.3100000500679014,-0.6314667353533269,1.041466731777048]);

% Plot in cross-section or along domain
postcrossplot(fem,0,[], ...
              'pointdata','tyns', ...
              'title','tyns', ...
              'axislabel',{'Time','tyns'}, ...
              'refine','auto');

% Plot in cross-section or along domain
postcrossplot(fem,0,[], ...
              'pointdata','tyns', ...
              'title','tyns', ...
              'axislabel',{'Time','tyns'}, ...
              'refine','auto');

% Plot in cross-section or along domain
postcrossplot(fem,0,[3,4,5,6], ...
              'pointdata','tyns', ...
              'title','tyns', ...
              'axislabel',{'Time','tyns'}, ...
              'refine','auto');

% Plot in cross-section or along domain
postcrossplot(fem,0,[3,4,5,6], ...
              'pointdata','tyns', ...
              'title','tyns', ...
              'axislabel',{'Time','tyns'}, ...
              'refine','auto');

% COMSOL Multiphysics Model M-file
% Generated by COMSOL 3.5a (COMSOL 3.5.0.608, $Date: 2009/05/11 07:38:49 $)

% (Default values are not included)

% Application mode 1
clear appl
appl.mode.class = 'FlNavierStokes';
appl.gporder = {4,2};
appl.cporder = {2,1};
appl.assignsuffix = '_ns';
clear bnd
bnd.u0 = {'4*Umax*y*(0.41-y)/(0.41*0.41)',0,0};
bnd.type = {'inlet','walltype','outlet'};
bnd.velType = {'u0','U0in','U0in'};
bnd.outtype = {'p','p','ntotstress'};
bnd.ind = [1,2,2,3,2,2,2,2];
appl.bnd = bnd;
clear equ
equ.eta = 0.001;
equ.gporder = {{1;1;2}};
equ.cporder = {{1;1;2}};
equ.cdon = 0;
equ.sdon = 0;
equ.ind = [1];
appl.equ = equ;
fem.appl{1} = appl;

% Application mode 2
clear appl
appl.mode.class = 'FlConvCond';
appl.sshape = 2;
appl.assignsuffix = '_cc';
clear prop
prop.analysis='static';
clear weakconstr
weakconstr.value = 'off';
weakconstr.dim = {'lm4'};
prop.weakconstr = weakconstr;
appl.prop = prop;
clear bnd
bnd.type = {'qc','T','T'};
bnd.T0 = {273.15,273,323};
bnd.ind = [2,2,2,1,3,3,3,3];
appl.bnd = bnd;
clear equ
equ.C = 800;
equ.rho = 1;
equ.init = 273;
equ.k = 40;
equ.u = '4*Umax*y*(0.41-y)/(0.41*0.41)';
equ.ind = [1];
appl.equ = equ;
fem.appl{2} = appl;
fem.frame = {'ref'};
fem.border = 1;
clear units;
units.basesystem = 'SI';
fem.units = units;

% Coupling variable elements
clear elemcpl
% Integration coupling variables
clear elem
elem.elem = 'elcplscalar';
elem.g = {'1'};
src = cell(1,1);
clear bnd
bnd.expr = {{{},'T_y_ns'}};
bnd.ipoints = {{{},'4'}};
bnd.frame = {{{},'ref'}};
bnd.ind = {{'1','2','3','4'},{'5','6','7','8'}};
src{1} = {{},bnd,{}};
elem.src = src;
geomdim = cell(1,1);
geomdim{1} = {};
elem.geomdim = geomdim;
elem.var = {'tyns'};
elem.global = {'1'};
elem.maxvars = {};
elemcpl{1} = elem;
fem.elemcpl = elemcpl;

% ODE Settings
clear ode
clear units;
units.basesystem = 'SI';
ode.units = units;
fem.ode=ode;

% Multiphysics
fem=multiphysics(fem);

% COMSOL Multiphysics Model M-file
% Generated by COMSOL 3.5a (COMSOL 3.5.0.608, $Date: 2009/05/11 07:38:49 $)

% (Default values are not included)

% Application mode 1
clear appl
appl.mode.class = 'FlNavierStokes';
appl.gporder = {4,2};
appl.cporder = {2,1};
appl.assignsuffix = '_ns';
clear bnd
bnd.u0 = {'4*Umax*y*(0.41-y)/(0.41*0.41)',0,0};
bnd.type = {'inlet','walltype','outlet'};
bnd.velType = {'u0','U0in','U0in'};
bnd.outtype = {'p','p','ntotstress'};
bnd.ind = [1,2,2,3,2,2,2,2];
appl.bnd = bnd;
clear equ
equ.eta = 0.001;
equ.gporder = {{1;1;2}};
equ.cporder = {{1;1;2}};
equ.cdon = 0;
equ.sdon = 0;
equ.ind = [1];
appl.equ = equ;
fem.appl{1} = appl;

% Application mode 2
clear appl
appl.mode.class = 'FlConvCond';
appl.sshape = 2;
appl.assignsuffix = '_cc';
clear prop
prop.analysis='static';
clear weakconstr
weakconstr.value = 'off';
weakconstr.dim = {'lm4'};
prop.weakconstr = weakconstr;
appl.prop = prop;
clear bnd
bnd.type = {'qc','T','T'};
bnd.T0 = {273.15,273,323};
bnd.ind = [2,2,2,1,3,3,3,3];
appl.bnd = bnd;
clear equ
equ.C = 800;
equ.rho = 1;
equ.init = 273;
equ.k = 40;
equ.v = 'v';
equ.u = 'u';
equ.ind = [1];
appl.equ = equ;
fem.appl{2} = appl;
fem.frame = {'ref'};
fem.border = 1;
clear units;
units.basesystem = 'SI';
fem.units = units;

% Coupling variable elements
clear elemcpl
% Integration coupling variables
clear elem
elem.elem = 'elcplscalar';
elem.g = {'1'};
src = cell(1,1);
clear bnd
bnd.expr = {{{},'T_y_ns'}};
bnd.ipoints = {{{},'4'}};
bnd.frame = {{{},'ref'}};
bnd.ind = {{'1','2','3','4'},{'5','6','7','8'}};
src{1} = {{},bnd,{}};
elem.src = src;
geomdim = cell(1,1);
geomdim{1} = {};
elem.geomdim = geomdim;
elem.var = {'tyns'};
elem.global = {'1'};
elem.maxvars = {};
elemcpl{1} = elem;
fem.elemcpl = elemcpl;

% ODE Settings
clear ode
clear units;
units.basesystem = 'SI';
ode.units = units;
fem.ode=ode;

% Multiphysics
fem=multiphysics(fem);

% Extend mesh
fem.xmesh=meshextend(fem);

% Mapping current solution to extended mesh
init = asseminit(fem,'init',fem0.sol,'xmesh',fem0.xmesh,'blocksize','auto');

% Update model
fem.sol = init;

% Save current fem structure for restart purposes
fem0=fem;

% Plot solution
postplot(fem, ...
         'tridata',{'U_ns','cont','internal','unit','m/s'}, ...
         'trimap','Rainbow', ...
         'title','Time=3.5    Surface: Velocity field [m/s]', ...
         'axis',[-0.12819549150036705,2.328195539184083,-0.6314667353533268,1.041466731777048]);

% COMSOL Multiphysics Model M-file
% Generated by COMSOL 3.5a (COMSOL 3.5.0.608, $Date: 2009/05/11 07:38:49 $)

% (Default values are not included)

% Application mode 1
clear appl
appl.mode.class = 'FlNavierStokes';
appl.gporder = {4,2};
appl.cporder = {2,1};
appl.assignsuffix = '_ns';
clear bnd
bnd.u0 = {'4*Umax*y*(0.41-y)/(0.41*0.41)',0,0};
bnd.type = {'inlet','walltype','outlet'};
bnd.velType = {'u0','U0in','U0in'};
bnd.outtype = {'p','p','ntotstress'};
bnd.ind = [1,2,2,3,2,2,2,2];
appl.bnd = bnd;
clear equ
equ.eta = 0.001;
equ.gporder = {{1;1;2}};
equ.cporder = {{1;1;2}};
equ.cdon = 0;
equ.sdon = 0;
equ.ind = [1];
appl.equ = equ;
fem.appl{1} = appl;

% Application mode 2
clear appl
appl.mode.class = 'FlConvCond';
appl.assignsuffix = '_cc';
clear prop
clear weakconstr
weakconstr.value = 'off';
weakconstr.dim = {'lm4'};
prop.weakconstr = weakconstr;
appl.prop = prop;
clear bnd
bnd.type = {'qc','T','T'};
bnd.T0 = {273.15,273,323};
bnd.ind = [2,2,2,1,3,3,3,3];
appl.bnd = bnd;
clear equ
equ.C = 800;
equ.rho = 1;
equ.init = 273;
equ.k = 40;
equ.v = 'v';
equ.u = 'u';
equ.ind = [1];
appl.equ = equ;
fem.appl{2} = appl;
fem.frame = {'ref'};
fem.border = 1;
clear units;
units.basesystem = 'SI';
fem.units = units;

% Coupling variable elements
clear elemcpl
% Integration coupling variables
clear elem
elem.elem = 'elcplscalar';
elem.g = {'1'};
src = cell(1,1);
clear bnd
bnd.expr = {{{},'T_y_ns'}};
bnd.ipoints = {{{},'4'}};
bnd.frame = {{{},'ref'}};
bnd.ind = {{'1','2','3','4'},{'5','6','7','8'}};
src{1} = {{},bnd,{}};
elem.src = src;
geomdim = cell(1,1);
geomdim{1} = {};
elem.geomdim = geomdim;
elem.var = {'tyns'};
elem.global = {'1'};
elem.maxvars = {};
elemcpl{1} = elem;
fem.elemcpl = elemcpl;

% ODE Settings
clear ode
clear units;
units.basesystem = 'SI';
ode.units = units;
fem.ode=ode;

% Multiphysics
fem=multiphysics(fem);

% Extend mesh
fem.xmesh=meshextend(fem);

% Update model
fem.sol = fem0.sol;

% Save current fem structure for restart purposes
fem0=fem;

% Plot solution
postplot(fem, ...
         'tridata',{'U_ns','cont','internal','unit','m/s'}, ...
         'trimap','Rainbow', ...
         'title','Time=3.5    Surface: Velocity field [m/s]', ...
         'axis',[-0.1100000023841858,2.310000050067902,-0.6723442575641881,1.0823442539879096]);

% (Default values are not included)

% Application mode 1
clear appl
appl.mode.class = 'FlNavierStokes';
appl.gporder = {4,2};
appl.cporder = {2,1};
appl.assignsuffix = '_ns';
clear bnd
bnd.u0 = {'4*Umax*y*(0.41-y)/(0.41*0.41)',0,0};
bnd.type = {'inlet','walltype','outlet'};
bnd.velType = {'u0','U0in','U0in'};
bnd.outtype = {'p','p','ntotstress'};
bnd.ind = [1,2,2,3,2,2,2,2];
appl.bnd = bnd;
clear equ
equ.eta = 0.001;
equ.gporder = {{1;1;2}};
equ.cporder = {{1;1;2}};
equ.cdon = 0;
equ.sdon = 0;
equ.ind = [1];
appl.equ = equ;
fem.appl{1} = appl;

% Application mode 2
clear appl
appl.mode.class = 'FlConvCond';
appl.assignsuffix = '_cc';
clear prop
clear weakconstr
weakconstr.value = 'off';
weakconstr.dim = {'lm4'};
prop.weakconstr = weakconstr;
appl.prop = prop;
clear bnd
bnd.type = {'qc','T','T'};
bnd.T0 = {273.15,273,323};
bnd.ind = [2,2,2,1,3,3,3,3];
appl.bnd = bnd;
clear equ
equ.C = 800;
equ.rho = 1;
equ.init = 273;
equ.k = 40;
equ.v = 'v';
equ.u = 'u';
equ.ind = [1];
appl.equ = equ;
fem.appl{2} = appl;
fem.frame = {'ref'};
fem.border = 1;
clear units;
units.basesystem = 'SI';
fem.units = units;

% Coupling variable elements
clear elemcpl
% Integration coupling variables
clear elem
elem.elem = 'elcplscalar';
elem.g = {'1'};
src = cell(1,1);
clear bnd
bnd.expr = {{{},'T_y_ns'}};
bnd.ipoints = {{{},'4'}};
bnd.frame = {{{},'ref'}};
bnd.ind = {{'1','2','3','4'},{'5','6','7','8'}};
src{1} = {{},bnd,{}};
elem.src = src;
geomdim = cell(1,1);
geomdim{1} = {};
elem.geomdim = geomdim;
elem.var = {'tyns'};
elem.global = {'1'};
elem.maxvars = {};
elemcpl{1} = elem;
fem.elemcpl = elemcpl;

% ODE Settings
clear ode
clear units;
units.basesystem = 'SI';
ode.units = units;
fem.ode=ode;

% Multiphysics
fem=multiphysics(fem);

% Extend mesh
fem.xmesh=meshextend(fem);

% Solve problem
fem.sol=femtime(fem, ...
                'init',fem0.sol, ...
                'symmetric','off', ...
                'solcomp',{'v','T','u','p'}, ...
                'outcomp',{'v','T','u','p'}, ...
                'blocksize','auto', ...
                'odesolver','genalpha', ...
                'tlist',[colon(0,0.025,3.5)], ...
                'estrat',1, ...
                'tout','tlist', ...
                'tsteps','manual', ...
                'rhoinf',0.5, ...
                'timestep','5*dt_cfl_g1_ns', ...
                'nlsolver','manual', ...
                'ntolfact',1, ...
                'maxiter',5, ...
                'dtech','const', ...
                'damp',1.0, ...
                'jtech','once', ...
                'uscale','none');

% Save current fem structure for restart purposes
fem0=fem;

% Plot solution
postplot(fem, ...
         'tridata',{'U_ns','cont','internal','unit','m/s'}, ...
         'trimap','Rainbow', ...
         'solnum','end', ...
         'title','Time=3.5    Surface: Velocity field [m/s]', ...
         'axis',[-0.1100000023841858,2.310000050067902,-0.6723442575641881,1.0823442539879096]);

% Plot solution
postplot(fem, ...
         'tridata',{'T','cont','internal','unit','K'}, ...
         'trimap','Rainbow', ...
         'solnum','end', ...
         'title','Time=3.5    Surface: Temperature [K]', ...
         'axis',[-0.1100000023841858,2.310000050067902,-0.6723442575641881,1.0823442539879096]);

% Plot solution
postplot(fem, ...
         'tridata',{'T','cont','internal','unit','K'}, ...
         'trimap','Rainbow', ...
         'solnum','end', ...
         'title','Time=3.5    Surface: Temperature [K]', ...
         'axis',[-0.12130841384424214,2.3213084615279582,-0.6723442575641881,1.0823442539879096]);

% Plot solution
postplot(fem, ...
         'tridata',{'T','cont','internal','unit','K'}, ...
         'trimap','Rainbow', ...
         'solnum','end', ...
         'title','Time=3.5    Surface: Temperature [K]', ...
         'axis',[-0.12130841384424214,2.3213084615279582,-0.6723442575641881,1.0823442539879096]);

return; %%%%%%%%%%% END OF HISTORY %%%%%%%%%%%%%%%%%%%%%%%
%                                                        %
% M-file below is used when resetting the model.         %
%                                                        %
%%%%%%%%%%%%%% START OF RESET HISTORY %%%%%%%%%%%%%%%%%%%%









% COMSOL Multiphysics Model M-file
% Generated by COMSOL 3.5a (COMSOL 3.5.0.608, $Date: 2009/05/11 07:38:49 $)

flclear fem

% COMSOL version
clear vrsn
vrsn.name = 'COMSOL 3.5';
vrsn.ext = 'a';
vrsn.major = 0;
vrsn.build = 608;
vrsn.rcs = '$Name: v35ap $';
vrsn.date = '$Date: 2009/05/11 07:38:49 $';
fem.version = vrsn;

% Geometry
g1=rect2(1,1,'base','corner','pos',[0,-0.8]);
g2=rect2('2.2','0.41','base','corner','pos',{'0','0'},'rot','0');
g3=ellip2(0.2,0.2,'base','center','pos',[-0.2,-0.2]);
g4=ellip2('0.05','0.05','base','center','pos',{'0.20','0.2'},'rot','0');
g5=geomcomp({g2,g4},'ns',{'R1','E1'},'sf','R1-E1','edge','none');

% Analyzed geometry
clear s
s.objs={g5};
s.name={'CO1'};
s.tags={'g5'};

fem.draw=struct('s',s);
fem.geom=geomcsg(fem);

% Constants
fem.const = {'Umax','0.3'};
% COMSOL Multiphysics Model M-file
% Generated by COMSOL 3.5a (COMSOL 3.5.0.608, $Date: 2009/05/11 07:38:49 $)

% Constants
fem.const = {'Umax','3.0'};
